close all;
clear;
clc;
addpath([cd '/data']);
addpath([cd '/detection']);
addpath([cd '/common']);
addpath([cd '/Threshold']);
addpath([cd '/GUI_BSP']);
addpath([cd '/Forms']);
addpath([cd '/GaussianFit']);
run MainForm.m;